const DATA = {
  meta:{ project:"型テスト", date:"2026-09-05", basis:"基準日 2026-09-05" },
  legend:[{cls:"t-off",label:"確認済みの事実"},{cls:"t-news",label:"報道"},{cls:"t-unk",label:"未確定"},{cls:"t-hyp",label:"整理"}],
  slides:[
  {id:"S0", t:"T", eyebrow:"hook", type:"hook", h:"見出しの<b>青</b>と<em>橙</em>", sub:"副題です。", src:"出典"},
  {id:"S1", t:"T", eyebrow:"specs", type:"specs", h:"specs の見出し", cards:[
    {cls:"off",tcls:"t-off",tag:"確認",k:"キー1",v:"45台",u:"補足1"},
    {cls:"news",tcls:"t-news",tag:"報道",k:"キー2",v:"約1,000",u:"補足2"},
    {cls:"unk",tcls:"t-unk",tag:"未確定",k:"キー3",v:"2,500",u:"補足3"},
    {cls:"off",tcls:"t-off",tag:"確認",k:"キー4",v:"12.5万",u:"補足4"}],
   foot:"specs のフッター。", src:"出典"},
  {id:"S2", t:"T", eyebrow:"specs2", type:"specs2", h:"specs2 の見出し", cards:[
    {cls:"off",tcls:"t-off",tag:"A",k:"キー1",v:"100万",u:"単位"},
    {cls:"off",tcls:"t-off",tag:"B",k:"キー2",v:"38万",u:"単位"},
    {cls:"news",tcls:"t-news",tag:"C",k:"キー3",v:"62万",u:"単位"},
    {cls:"unk",tcls:"t-unk",tag:"D",k:"キー4",v:"6都市",u:"単位"}],
   foot:"specs2 のフッター。", src:"出典"},
  {id:"S3", t:"T", eyebrow:"units", type:"units", h:"units の見出し",
   units:[{u:"TWh",n:"テラワット時",d:"量を表す単位。"},{u:"kW",n:"キロワット",d:"出力を表す単位。"}],
   foot:"units のフッター。", src:"出典"},
  {id:"S4", t:"T", eyebrow:"ratio", type:"ratio", h:"ratio の見出し",
   bar:{a:{flex:88,big:"約1TWh／年",sub:"対象になる範囲（約88%）"},b:{flex:12,label:"約12%"}},
   ends:["全体：年間1.1TWh超","残りは別主体が取引"],
   cards:[{cls:"unk",k:"やってはいけない",big:"A ＋ B",note:"合計値ではありません。",strike:1},
          {cls:"off",k:"正しい言い方",big:"A のみ",note:"1件の契約規模です。"}],
   src:"出典"},
  {id:"S5", t:"T", eyebrow:"unitbig", type:"unitbig", h:"unitbig の見出し", cards:[
    {cls:"off",tcls:"t-off",tag:"正しい",big:"10<span style='font-size:70px'>億</span>kWh",note:"量を表す単位。"},
    {cls:"unk",tcls:"t-unk",tag:"誤り",big:"1兆W",note:"出力と量は置き換えられません。",strike:1},
    {cls:"news",tcls:"t-news",tag:"目安",k:"一般家庭でいうと",big:"230",mid:1,note:"万世帯（制作者による試算）。"}],
   src:"出典"},
  {id:"S6", t:"T", eyebrow:"city", type:"city", h:"city の見出し", cards:[
    {cls:"off",tcls:"t-news",tag:"報道",k:"開発会社の説明",mid:"10〜12万人",note:"規模の都市の家庭需要に相当。"},
    {cls:"unk",tcls:"t-unk",tag:"言ってはいけない",k:"誇張になる言い方",mid:"都市の総需要",strike:1,note:"工場やオフィスを含む総需要ではありません。"}],
   dots:{n:40,on:36,per:20,label:"■＝家庭部門　／　うち約90%が対象"},
   src:"出典"},
  {id:"S7", t:"T", eyebrow:"ownbuy", type:"ownbuy", h:"ownbuy の見出し",
   left:{cls:"unk",tcls:"t-unk",tag:"今回ではない",ttl:"発電所の所有",items:["資産として保有する","運転と保守の責任を負う","貸借対照表に載る"]},
   right:{cls:"off",tcls:"t-off",tag:"今回はこちら",ttl:"電力の長期購入",items:["発電所は開発会社が所有","買うのは発電された電力","期間と量を先に決める"]},
   src:"出典"},
  {id:"S8", t:"T", eyebrow:"table", type:"table", h:"table の見出し",
   cols:["時期","出来事","意味"],
   rows:[["2022年","資料提出の命令","根拠を問われた"],["2023年","監査照会を開設","同じ手続き"],["2026年7月","免除の最終承認","道を切り替えた"],["その後","有料サービス開始","枠内で運行"],["現在","継続中","注視"]],
   foot:"table のフッター。", src:"出典"},
  {id:"S9", t:"T", eyebrow:"flow", type:"flow", h:"flow の見出し",
   steps:[{cls:"news",t:"Starship",d:"売る製品ではない"},{cls:"off",t:"Starlink",d:"加入者からの収入"},{cls:"unk",t:"売上・利益",d:"ここで業績になる"}],
   labels:["運ぶ","積み上がる"],
   foot:"flow のフッター。", src:"出典"},
  {id:"S10", t:"T", eyebrow:"chain", type:"chain", h:"chain の見出し",
   steps:[{cls:"off",t:"技術",d:"成功する",d2:"実証の段階"},{cls:"news",t:"運用",d:"繰り返せる",d2:"再現性の段階"},{cls:"unk",t:"収益",d:"数字に出る",d2:"業績の段階"}],
   labels:["→","→"], src:"出典"},
  {id:"S11", t:"T", eyebrow:"ladder", type:"ladder", h:"ladder の見出し",
   steps:[{cls:"news",t:"技術が成功する",v:"いまここ"},{t:"運用として繰り返せる"},{t:"展開の規模が上がる"},{t:"収益になる"},{t:"業績の数字に出る"},{cls:"off",t:"株価の評価が変わる",v:"最終段"}],
   foot:"ladder のフッター。", src:"出典"},
  {id:"S12", t:"T", eyebrow:"flow2", type:"flow2", h:"flow2 の見出し",
   steps:[{cls:"off",t:"申請",d:"書類を出す"},{cls:"off",t:"審査",d:"当局が確認"},{cls:"news",t:"意見公募",d:"公開で募る"},{cls:"news",t:"認可",d:"条件つき"},{cls:"unk",t:"運行",d:"上限あり"},{cls:"unk",t:"更新",d:"期限つき"}],
   foot:"flow2 のフッター。", src:"出典"},
  {id:"S13", t:"T", eyebrow:"pricechart", type:"pricechart", h:"pricechart の見出し",
   points:[{x:"6/12",t:"IPO",v:135,val:"$135.00",cls:"news"},{x:"6/16",t:"高値",v:225.64,val:"$225.64",cls:"off"},{x:"7/28",t:"安値",v:107.01,val:"$107.01",cls:"unk"},{x:"7/30",t:"直近",v:112.12,val:"$112.12",cls:"news"}],
   hline:135, hlabel:"IPO価格 $135",
   foot:"高値からは約50%下、IPO価格からは約17%下。", src:"出典"},
  {id:"S14", t:"T", eyebrow:"subtract", type:"subtract", h:"subtract の見出し",
   bars:[{v:48000,val:"48,000",t:"年間の輸入能力",cls:"off"},{v:10600,val:"10,600",t:"実際の納車",cls:"news"}],
   foot:"輸入能力は、実績のおよそ4.5倍。", src:"出典"},
  {id:"S15", t:"T", eyebrow:"timeline", type:"timeline", h:"timeline の見出し",
   points:[{d:"2025年",t:"実証目的の適用除外",cls:"unk"},{d:"2026年3月",t:"意見公募を開始",cls:"news"},{d:"2026年7月",t:"商用展開を認可",cls:"off"}],
   gaps:["約1年","約5か月"],
   foot:"timeline のフッター。", src:"出典"},
  {id:"S16", t:"T", eyebrow:"three", type:"three", h:"three の見出し",
   three:[{cls:"news",ttl:"01",tag:"AAA",items:["項目1","項目2","項目3"]},
          {cls:"news",ttl:"02",tag:"BBB",items:["項目1","項目2","項目3"]},
          {cls:"off",ttl:"03",tag:"CCC",items:["項目1","項目2","項目3"]}],
   src:"出典"},
  {id:"S17", t:"T", eyebrow:"rows 7行", type:"rows", h:"rows の7行テスト",
   rows:[{cls:"off",n:"01",t:"1行目のテキスト",v:"45台"},{cls:"off",n:"02",t:"2行目のテキスト",v:"約375台"},
         {cls:"news",n:"03",t:"3行目のテキスト",v:"約1,000台"},{cls:"news",n:"04",t:"4行目のテキスト",v:"年2,500台"},
         {cls:"unk",n:"05",t:"5行目のテキスト",v:"12.5万台超"},{cls:"unk",n:"06",t:"6行目のテキスト",v:"未確定"},
         {cls:"unk",n:"07",t:"7行目のテキスト",v:"未確定"}],
   src:"出典"},
  {id:"S18", t:"T", eyebrow:"rows 6行＋foot", type:"rows", h:"rows の6行＋フッター",
   rows:[{cls:"off",n:"01",t:"1行目",v:"A"},{cls:"off",n:"02",t:"2行目",v:"B"},{cls:"news",n:"03",t:"3行目",v:"C"},
         {cls:"news",n:"04",t:"4行目",v:"D"},{cls:"unk",n:"05",t:"5行目",v:"E"},{cls:"unk",n:"06",t:"6行目",v:"F"}],
   foot:"6行でもフッターと凡例に重ならないこと。", src:"出典"},
  {id:"S30", t:"T", eyebrow:"rows 5行＋foot", type:"rows", h:"rows の5行＋フッター",
   rows:[{cls:"off",n:"01",t:"1行目",v:"A"},{cls:"off",n:"02",t:"2行目",v:"B"},{cls:"news",n:"03",t:"3行目",v:"C"},
         {cls:"news",n:"04",t:"4行目",v:"D"},{cls:"unk",n:"05",t:"5行目",v:"E"}],
   foot:"5行でもフッターと出典が重ならないこと。", src:"出典"},
  {id:"S19", t:"T", eyebrow:"rows 4行", type:"rows", h:"rows の4行（従来の中央寄せ）",
   rows:[{cls:"off",n:"01",t:"1行目",v:"A"},{cls:"off",n:"02",t:"2行目",v:"B"},{cls:"news",n:"03",t:"3行目",v:"C"},{cls:"unk",n:"04",t:"4行目",v:"D"}],
   src:"出典"},
  {id:"S20", t:"T", eyebrow:"ps", type:"ps", h:"ps の見出し",
   points:["特徴1のテキスト","特徴2のテキスト","特徴3のテキスト"], brand:"ブランド名／概要欄のリンクから", src:"出典"},
  {id:"S21", t:"T", eyebrow:"split", type:"split", h:"split の見出し",
   left:{cls:"off",ttl:"左の見出し",items:["項目1","項目2","項目3","項目4"]},
   right:{cls:"news",ttl:"右のラベル",big:"2,500",sub:"補足のテキストです。"},
   foot:"split のフッター。", src:"出典"},
  {id:"S22", t:"T", eyebrow:"twocol", type:"twocol", h:"twocol の見出し",
   left:{cls:"unk",ttl:"左",body:"本文。<b>太字</b>と<br>改行が使えます。"},
   right:{cls:"off",ttl:"右",body:"本文。"},
   foot:"twocol のフッター。", src:"出典"},
  {id:"S23", t:"T", eyebrow:"statement", type:"statement", h:"statement の見出し",
   points:["箇条書き1","箇条書き2","箇条書き3"], foot:"statement のフッター。", src:"出典"},
  {id:"S24", t:"T", eyebrow:"quote", type:"quote", h:"quote の見出し",
   quote:"引用される発言や通知の本文がここに入ります。長さは2行程度を想定しています",
   note:"引用の補足。<br>2行目の補足。", src:"出典"},
  {id:"S25", t:"T", eyebrow:"chart", type:"chart", cls:"off", img:"cc4", h:"chart の見出し",
   points:["注釈1","注釈2","注釈3"], foot:"chart のフッター。", src:"出典"},
  {id:"S26", t:"T", eyebrow:"photo", type:"photo", cls:"off", img:"cc2", h:"photo の見出し",
   points:["注釈1","注釈2","注釈3","注釈4"], foot:"photo のフッター。", src:"出典"},
  {id:"S27", t:"T", eyebrow:"concl2", type:"concl2", h:"concl2 の見出し",
   concl:[{cls:"off",ttl:"見出しA",txt:"本文A。"},{cls:"news",ttl:"見出しB",txt:"本文B。"},{cls:"unk",ttl:"見出しC",txt:"本文C。"}],
   foot:"concl2 のフッター。", src:"出典"},
  {id:"S28", t:"T", eyebrow:"cta", type:"cta", h:"cta の見出し",
   points:["高評価","チャンネル登録","毎日発信"], foot:"締めの一文。", src:"出典"},
  {id:"S29", t:"T", eyebrow:"concl", type:"concl", h:"concl の見出し",
   concl:[{cls:"off",ttl:"見出しA",txt:"本文A。"},{cls:"news",ttl:"見出しB",txt:"本文B。"},{cls:"unk",ttl:"見出しC",txt:"本文C。"}],
   foot:"concl のフッター。", src:"出典"}
  ]
};
